# Generated by Django 3.2.7 on 2021-10-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
    ]
