# Generated by Django 3.2.7 on 2021-11-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='image', max_length=30, upload_to=''),
            preserve_default=False,
        ),
    ]
